### ISSUE TITLE
Unable to access osticket page

### ISSUE THREAD

**Issue by nathphoenix** [VincentSC/osTicket-Docker#2]
Hello @VincentSC Trust you having a great weekend,
Really happy to have come across your implementation
please i have followed your step to setup osticket, but i'm unable to access the platform while all docker containers services are running perfectly, please can you help out?
Thank you

**Comment by VincentSC** [comment]
Be aware it assumes an nginx-proxy. If you use another system, it won't work.

For the rest: I can't guess your logs and config :)

**Comment by nathphoenix** [comment]
I really appreciate your response, i think i found twhat is causing it,
i execute the container and also check the logs then i realise that the init_storage.sh file was missing which is the entry point to the app.

from the docker file :  CMD /var/www/html/init_storage.sh; cron; apache2-foreground

But for the nginx part, i remove the network and setup my own nginx to serve the application which is working, and the reason i remove nignx-proxy is because there was an error coming up because nginx-proxy network was set to external which hinder all containers from running, but left the default network

BELOW IS THE ERROR FROM THE CONTAINER LOGS

```
/bin/sh: 1: /var/www/html/init_storage.sh: not found
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message
```

**Comment by nathphoenix** [comment]
Hi @VincentSC another major problem i realise now is that the bash script is no longer working as expected, there has been some changes which is why the osticket.zip file is failing to download and then unzip.

**Comment by VincentSC** [comment]
Yeah, seems that `get-latest.sh` did not run correctly. I don't see the changes myself.

Got an error?

**Comment by nathphoenix** [comment]
Thanks i have resolve, i had to download osticket without the bash file....

**Comment by nathphoenix** [comment]
> Yeah, seems that `get-latest.sh` did not run correctly. I don't see the changes myself.
> 
> Got an error?

The wget wasn't able to download, that should be because there is an update to bash syntax, 
But i have completed the setup, i can deploy now, 
Thanks so much!!!

**Comment by VincentSC** [comment]
As I moved to osticketawesome and made most changes for that, so I cannot easily maintain this code. I checked the code I made available - yes, it probably needed some manual work to get going, as I put e.g. some version-checks in there.

Good you got it working!
